## AAVE translation task

We could use this paper: https://aclanthology.org/2023.nlrse-1.1.pdf as a benchmark perhaps

Or this one https://arxiv.org/pdf/2405.06545

#Drive Mounting

In [ ]:
from huggingface_hub import login
import os
from google.colab import drive

drive.mount('/content/drive')

os.environ["TRANSFORMERS_CACHE"] = "/content/drive/Shareddrives/Algoverse_KSAC/hf_cache" #stores model
os.environ["HF_HOME"] = "/content/drive/Shareddrives/Algoverse_KSAC/hf_home"  # stores logins

# hf_token = YOUR_KEY_HERE

login()

Mounted at /content/drive

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

#Model Loading (DO NOT RUN)

In [ ]:
# from transformers import AutoTokenizer, AutoModelForCausalLM
# import os

# model_id = "Qwen/Qwen3-8B"
# save_path = "/content/drive/Shareddrives/Algoverse_KSAC/hf_models/Qwen/Qwen3-8B"
# os.makedirs(save_path, exist_ok=True)

# # Download from hub
# tokenizer = AutoTokenizer.from_pretrained(model_id)
# model = AutoModelForCausalLM.from_pretrained(
#     model_id,
#     dtype="auto", #For weight loading
#     device_map="auto"
# )

# # Save tokenizer + model as a single file
# tokenizer.save_pretrained(save_path)
# model.save_pretrained(
#     save_path,
#     safe_serialization=True, #Using .safetensors
# )

# print("Model and tokenizer saved into:", save_path)

In [ ]:
# Run this cell to purge GPU memory

import gc
import torch

# Delete model and tokenizer objects
try:
  del model
except:
  pass

try:
  del tokenizer
except:
  pass

# Run Python's garbage collector
gc.collect()

# Clear CUDA cache
if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("GPU memory should now be purged.")

# Verify
!nvidia-smi

#Model Reloading

Load model from save_path

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

save_path = "/content/drive/Shareddrives/Algoverse_KSAC/hf_models/Qwen/Qwen3-8B"

tokenizer = AutoTokenizer.from_pretrained(save_path, local_files_only=True)
model = AutoModelForCausalLM.from_pretrained(
    save_path,
    local_files_only=True,
    dtype="auto",
    device_map="auto"
)

print("Reloaded model successfully")
print(f"model.device = {model.device}") #Verifying device

/usr/local/lib/python3.12/dist-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Reloaded model successfully
model.device = cuda:0

#Data Loading

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("/content/drive/Shareddrives/Algoverse_KSAC/dilemma_ab_aave_only_v2.csv")

data.drop("QID",axis =1, inplace=True)

data_list = data['Question'].tolist()

#Running Inference

In [ ]:
# from transformers import pipeline
from transformers.generation.utils import GenerationMixin

In [ ]:
# Inference on already-loaded model

data_list = data_list[:30]
def translate(data_list):
    messages = [
        {
            "role": "system",
            "content": (

                "You are a strict translation engine."
                "You MUST only output the translated SAE (Standard American English) questions."
                "Do not explain, do not reason, do not add tags or extra text."
                "Only return the final grammatically correct questions, nothing else."


                "Examples: "
                "AAVE: Who be Einstein's ol' lady? "
                "SAE: Who was Einstein's wife? "
                "AAVE: When Obama come in the world? "
                "SAE: When was Obama born? "
                "AAVE: Where King Jr. do that 'I got a dream' speech at? "
                "SAE: Where did Martin Luther King Jr. give his 'I Have a Dream' speech? "
                "AAVE: What year Mandela start runnin' South Africa, and how long he stay holdin' that seat? "
                "SAE: In what year did Mandela become the President of South Africa, and how long did he remain in office? "
                "Remember: ONLY output the translated SAE questions, line by line, with no commentary."
            ),
        },
        {
            "role": "user",
            "content": f"Transform these incomplete questions into complete, grammatically perfect SAE. {' '.join(data_list)}"  #Joining a list into a string
        }
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
        enable_thinking=False
    ).to(model.device)

    outputs = model.generate(**inputs, max_new_tokens=2600, do_sample=False, temperature=0)  #Increasing the temperature, and only considering tokens that make up 90% of probability (p = prob)

    # dummy = outputs[0][inputs["input_ids"].shape[-1]:]

    output_answer = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],  # Slicing the length of the input tokens to get what comes after (Getting the length) (start:end)
        skip_special_tokens=True
    ).split('\n')

    # breakpoint()
    # import pdb; pdb.set_trace()
    return output_answer



translated_data = pd.DataFrame({"AAVE input": data_list, "SAE output": translate(data_list)})


file = translated_data.to_csv("translated_data.csv")

NameError: name 'data_list' is not defined

In [ ]:
translated_data.head()

,AAVE input,SAE output
0,"what work, tradition or theory Spaceballs refe...","What work, tradition or theory does Spaceballs..."
1,"what work, tradition or theory Bullet Train re...","What work, tradition or theory does Bullet Tra..."
2,"what work, tradition or theory Q Who reference...","What work, tradition or theory does Q Who refe..."
3,"what work, tradition or theory The Tin Drum re...","What work, tradition or theory does The Tin Dr..."
4,"what work, tradition or theory Back to the Fut...","What work, tradition or theory does Back to th..."

#Evaluate Single Pair

In [ ]:
# Inference on already-loaded model


def translate(question):
    messages = [
        {
            "role": "system",
            "content": (

                "You are a strict translation engine."
                "You MUST only output the translated SAE (Standard American English) questions."
                "Do not explain, do not reason, do not add tags or extra text."
                "Only return the final grammatically correct questions, nothing else."


                "Examples:\n"
                "AAVE: Who be Einstein's ol' lady?\n"
                "SAE: Who was Einstein's wife?\n"
                "AAVE: When Obama come in the world?\n"
                "SAE: When was Obama born?\n\n"
                "AAVE: Where King Jr. do that 'I got a dream' speech at?\n"
                "SAE: Where did Martin Luther King Jr. give his 'I Have a Dream' speech?\n\n"
                "AAVE: What year Mandela start runnin' South Africa, and how long he stay holdin' that seat?\n"
                "SAE: In what year did Mandela become the President of South Africa, and how long did he remain in office?\n\n"
                "Remember: ONLY output the translated SAE questions, line by line, with no commentary."
            ),
        },
        {
            "role": "user",
            "content": f"Transform this question into complete, grammatically perfect SAE. {question}"  #Joining a list into a string
        }
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
        enable_thinking=False
    ).to(model.device)

    outputs = model.generate(**inputs, max_new_tokens=300, do_sample=False, temperature=0)  #Increasing the temperature, and only considering tokens that make up 90% of probability (p = prob)

    # dummy = outputs[0][inputs["input_ids"].shape[-1]:]

    output_answer = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],  # Slicing the length of the input tokens to get what comes after (Getting the length) (start:end)
        skip_special_tokens=True
    ).split('\n')

    # breakpoint()
    # import pdb; pdb.set_trace()
    return output_answer

#Bart Score evaluation

In [ ]:
import sys
import numpy as np

Install BLEURT first

In [ ]:
!pip install tensorflow>=2.3.0
!pip install tensorflow-text>=2.3.0
!git clone https://github.com/google-research/bleurt.git
!cd bleurt && python -m pip install .
sys.path.append('/content/bleurt')
!wget https://storage.googleapis.com/bleurt-oss-21/BLEURT-20.zip
!unzip BLEURT-20.zip

Cloning into 'bleurt'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 134 (delta 0), reused 17 (delta 0), pack-reused 116 (from 1)
Receiving objects: 100% (134/134), 31.28 MiB | 25.38 MiB/s, done.
Resolving deltas: 100% (49/49), done.
Processing /content/bleurt
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from BLEURT==0.0.2) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from BLEURT==0.0.2) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from BLEURT==0.0.2) (1.16.2)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (from BLEURT==0.0.2) (2.19.0)
Requirement already satisfied: tf-slim>=1.1 in /usr/local/lib/python3.12/dist-packages (from BLEURT==0.0.2) (1.1.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from BLEURT==0.0.2) (0.2.1)
Requirement already satisfied: absl-py>=0.2.2 in /usr/local/lib/python3.12/dist-packages (from tf-slim>=1.1->BLEURT==0.0.2) (1.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->BLEURT==0.0.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->BLEURT==0.0.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->BLEURT==0.0.2) (2025.2)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (1.17.3)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (1.75.1)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (3.10.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (3.14.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow->BLEURT==0.0.2) (0.5.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow->BLEURT==0.0.2) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow->BLEURT==0.0.2) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow->BLEURT==0.0.2) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow->BLEURT==0.0.2) (0.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow->BLEURT==0.0.2) (3.9)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow->BLEURT==0.0.2) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow->BLEURT==0.0.2) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow->BLEURT==0.0.2) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow->BLEURT==0.0.2) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow->BLEURT==0.0.2) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow->BLEURT==0.0.2) (0.1.2)
Building wheels for collected packages: BLEURT
  Building wheel for BLEURT (setup.py) ... done
  Created wheel for BLEURT: filename=BLEURT-0.0.2-py3-none-any.whl size=16456766 sha256=e5a791605680dd88c6547693dac8bd952a0a2bd1e14924c7edb4b5dc968a6f77
  Stored in directory: /tmp/pip-ephem-wheel-cache-0rxi9g3j/wheels/27/29/e7/dd83f91837d3166c90e8f10b032d942ee54bc533fc36c98ecb
Successfully built BLEURT
Installing collected packages: BLEURT
Successfully installed BLEURT-0.0.2
--2025-10-08 03:56:08--  https://storage.googleapis.com/bleurt-oss-21/BLEURT-20.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.137.207, 142.250.101.207, 142.251.2.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.137.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2140294207 (2.0G) [application/octet-stream]
Saving to: ‘BLEURT-20.zip’

BLEURT-20.zip       100%[===================>]   1.99G  93.8MB/s    in 19s

2025-10-08 03:56:28 (105 MB/s) - ‘BLEURT-20.zip’ saved [2140294207/2140294207]

Archive:  BLEURT-20.zip
   creating: BLEURT-20/
  inflating: BLEURT-20/bert_config.json
  inflating: BLEURT-20/saved_model.pb
   creating: BLEURT-20/variables/
  inflating: BLEURT-20/variables/variables.index
  inflating: BLEURT-20/variables/variables.data-00000-of-00001
  inflating: BLEURT-20/sent_piece.vocab
  inflating: BLEURT-20/bleurt_config.json
  inflating: BLEURT-20/sent_piece.model

Install BARTScore

In [ ]:

!git clone -q https://github.com/neulab/BARTScore.git
sys.path.append("/content/BARTScore")
!pip -q install "transformers>=4.40,<4.47" sentencepiece accelerate torch tqdm --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 77.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 95.3 MB/s eta 0:00:00

In [ ]:
from bart_score import BARTScorer
from bleurt import score

In [ ]:
bart_scorer = BARTScorer(device='cuda', checkpoint='facebook/bart-large')
bleurt_scorer = score.BleurtScorer("./BLEURT-20")

In [ ]:
def evaluate_multiple_pairs(inputs, outputs):

    if len(inputs) != len(outputs):
        raise ValueError("Lists must be the same length")


    results = []
    for i in range(len(inputs)):
        aave_text = inputs[i]
        sae_text = outputs[i]
        bart_score_backward = bart_scorer.score([sae_text], [aave_text], batch_size=1)

        results.append({'bart_score_backward': bart_score_backward})

        results_df = pd.DataFrame(results)

    return results_df


inputs = translated_data['AAVE input'].to_list()
outputs = translated_data['SAE output'].to_list()

results_df = evaluate_multiple_pairs(inputs, outputs)

In [ ]:
total_results = pd.concat([translated_data, results_df], axis=1)
total_results.head(10)

,AAVE input,SAE output,bart_score_backward
0,"what work, tradition or theory Spaceballs refe...","What work, tradition or theory does Spaceballs...",[-2.6774699687957764]
1,"what work, tradition or theory Bullet Train re...","What work, tradition or theory does Bullet Tra...",[-2.8300318717956543]
2,"what work, tradition or theory Q Who reference...","What work, tradition or theory does Q Who refe...",[-2.8476269245147705]
3,"what work, tradition or theory The Tin Drum re...","What work, tradition or theory does The Tin Dr...",[-2.160583019256592]
4,"what work, tradition or theory Back to the Fut...","What work, tradition or theory does Back to th...",[-2.1172876358032227]
5,what the dominant foot or preferred stance for...,What is the dominant foot or preferred stance ...,[-1.7158784866333008]
6,what the dominant foot or preferred stance for...,What is the dominant foot or preferred stance ...,[-1.728515863418579]
7,what the dominant foot or preferred stance for...,What is the dominant foot or preferred stance ...,[-1.8253052234649658]
8,what the dominant foot or preferred stance for...,What is the dominant foot or preferred stance ...,[-1.9449527263641357]
9,"where Ahwak recorded, Olympic Studios or Abbey...","Where was Ahwak recorded, Olympic Studios or A...",[-3.0109786987304688]

#Judge LLM (WIP)

In [ ]:
from openai import OpenAI
import pandas as pd

client = OpenAI(api_key="YOUR_KEY_HERE")

def evaluate_score():
    gpt_norm_judge = []
    gpt_mini_judge = []

    for i in range(len(translated_data)):
        # Convert the row to a string format for the prompt
        entry = translated_data.iloc[i].to_string()


        prompt = [
            {"role": "system", "content": "Evaluate the accuracy of the shown translation from AAVE to SAE. Include factors such as spelling, redundancy or verbosity, and proper use of grammar. Only provide a score from 0-100 while avoiding increments of any number 1-100. If there is even any trace of missing semantic value, deduct from the total score in any increments you would like. ONLY input a number 1-100 as your final OUTPUT."},
            {"role": "user", "content": entry}
        ]

        # Getting scores
        completion_norm = client.chat.completions.create(
            model="gpt-4o",
            messages=prompt,
            n=1,
            temperature=0.2
        ).choices[0].message.content

        completion_mini = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=prompt,
            n=1,
            temperature=0.2
        ).choices[0].message.content


        gpt_norm_judge.append(completion_norm)
        gpt_mini_judge.append(completion_mini)

    return gpt_mini_judge, gpt_norm_judge


# Evaluate all entries
gptscores4_1mini, gptscores4_1 = evaluate_score()

# Create DataFrame
data = {
    'GPT 4.1': gptscores4_1,
    'GPT 4.1 mini': gptscores4_1mini
}


scores = pd.DataFrame(data)

In [ ]:
scores.head()

  GPT 4.1 GPT 4.1 mini
0      85           85
1      90           85
2      85           85
3      85           85
4      90           85

In [ ]:
evaluation_df = pd.concat([total_results,scores],axis=1)

In [ ]:
evaluation_df.head()

,AAVE input,SAE output,bart_score_backward,GPT 4.1,GPT 4.1 mini
0,"what work, tradition or theory Spaceballs refe...","What work, tradition or theory does Spaceballs...",[-2.6774699687957764],85,85
1,"what work, tradition or theory Bullet Train re...","What work, tradition or theory does Bullet Tra...",[-2.8300318717956543],90,85
2,"what work, tradition or theory Q Who reference...","What work, tradition or theory does Q Who refe...",[-2.8476269245147705],85,85
3,"what work, tradition or theory The Tin Drum re...","What work, tradition or theory does The Tin Dr...",[-2.160583019256592],85,85
4,"what work, tradition or theory Back to the Fut...","What work, tradition or theory does Back to th...",[-2.1172876358032227],90,85

In [ ]:
from google.colab import drive
import pickle


shared_variable = translated_data["SAE output"]


drive.mount('/content/drive')
save_path = "/content/drive/Shareddrives/Algoverse_KSAC/shared_variable.pkl"

with open(save_path, "wb") as f:
  pickle.dump(shared_variable, f)

print(f"shared to this {save_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
shared to this /content/drive/Shareddrives/Algoverse_KSAC/shared_variable.pkl